"""Label management for GitHub issues."""

from typing import Optional

from .github import ensure_label_exists

# Predefined label definitions
LABEL_DEFINITIONS: dict[str, dict[str, str]] = {
    "priority:high": {
        "color": "d73a4a",
        "description": "High priority - Must have",
    },
    "priority:medium": {
        "color": "fbca04",
        "description": "Medium priority - Should have",
    },
    "priority:low": {
        "color": "0e8a16",
        "description": "Low priority - Could have",
    },
    "priority:wont": {
        "color": "ffffff",
        "description": "Won't have",
    },
    "task": {
        "color": "1d76db",
        "description": "Implementation task from speckit",
    },
    "speckit": {
        "color": "7057ff",
        "description": "Generated by speckit-to-issue",
    },
}

# Color for dynamically generated phase labels
PHASE_LABEL_COLOR = "5319e7"

# Color for dynamically generated spec labels
SPEC_LABEL_COLOR = "c5def5"


def get_label_color(label: str) -> str:
    """Get the color for a label.

    Args:
        label: Label name

    Returns:
        Hex color code (without #)
    """
    if label in LABEL_DEFINITIONS:
        return LABEL_DEFINITIONS[label]["color"]
    if label.startswith("phase-"):
        return PHASE_LABEL_COLOR
    if label.startswith("spec:"):
        return SPEC_LABEL_COLOR
    return "ededed"  # Default gray


def ensure_labels(labels: list[str], repo: Optional[str] = None) -> dict[str, bool]:
    """Ensure all labels exist in the repository.

    Args:
        labels: List of label names
        repo: Repository in owner/repo format

    Returns:
        Dict mapping label name to success status
    """
    results: dict[str, bool] = {}
    for label in labels:
        color = get_label_color(label)
        results[label] = ensure_label_exists(label, color, repo)
    return results


def get_all_labels_for_tasks(tasks: list) -> set[str]:
    """Get all unique labels needed for a list of tasks.

    Args:
        tasks: List of Task objects

    Returns:
        Set of unique label names
    """
    labels: set[str] = {"task", "speckit"}

    for task in tasks:
        labels.add(task.priority_label)
        if task.phase_label:
            labels.add(task.phase_label)
        if task.spec_name:
            labels.add(task.spec_label)

    return labels
